language: ruby
env:
  global:
    secure: GKXELm3iiiVxv3hjNKvTeesXNLRJwGQo39S1SUSG8vJWgkxlidONcgtPa4sBweXPJTMY47o3F2gYnHb4yPMRrb/zxKnKVXBjPrTQPYqDUFOOGpj78n5k/QqVVeCgR/xl12f5RVOuCHMxF73fvCb6liVOaSZ72Wu6Qc/VTbM44O0=
rvm:
- 1.9.3
- 2.0.0
