name: Release
on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: GitHub Packages
      uses: jstastny/publish-gem-to-github@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        owner: alexgenco
    - name: RubyGems
      uses: cadwallion/publish-rubygems-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        RELEASE_COMMAND: bundle exec rake release
